---

- name: Download and install grafana apt public signing key
  apt_key:
    data: "{{ lookup('file', grafana_signing_key_data) }}"
    state: present

- name: Add grafana apt repository definition to apt sources list
  apt_repository: 
    repo:         "{{ grafana_apt_repo }}"
    update_cache: yes
    state:        present

- name: Install grafana
  apt:
    name:  "grafana={{ grafana_version|default('*') }}"
    state: present
  notify: Restart grafana
